name: iotdellgw
version: git
summary: iotdellgw sends gps data
description: |
  gps data sender

grade: devel
confinement: devmode

apps:
  iotdellgw:
    command: iotdellgw

parts:
  iotdellgw:
    plugin: python
    python-version: python2
    source: .

